export const INDUSTRIES = [
  'House cleaning',
  'Carpet cleaning',
  'Window cleaning',
  'Pressure washing',
  'Landscaping',
  'Tree service',
  'Pool service',
  'Pest control',
  'Junk removal',
  'Handyman',
  'Plumbing',
  'Electrical',
  'HVAC',
  'Appliance repair',
  'Garage door repair',
  'Mobile mechanic',
  'Mobile detailing',
  'Mobile tire service',
  'Tow / roadside',
  'Locksmith',
  'Massage therapy',
  'Pet grooming',
  'Dog walking / pet sitting',
  'House painting',
  'Airbnb turnover cleaning',
  'Other',
] as const;
